const { exec } = require('child_process');
const { promisify } = require('util');

const test = require('ava');
const uuid = require('uuid/v4');
const { Pool } = require('pg');

const execAsync = promisify(exec);
const update = require('../src/update');

test.before(async (t) => {
  t.context.db = uuid();
  await execAsync(`createdb ${t.context.db}`);
  t.context.pool = new Pool({
    database: t.context.db
  });

  await t.context.pool.query(`
    create table user_account (
      user_account_id integer primary key generated by default as identity,
      first_name text,
      last_name text
    );
  `);
  await t.context.pool.query(`
    insert into user_account (first_name, last_name) values ('Joe', 'Smith')
  `);
});

test('update - Case 1', async (t) => {
  const actual = await update({
    pool: t.context.pool,
    table: 'user_account',
    values: {firstName: 'Jim', lastName: 'Jenkins'},
    where: {userAccountId: 1},
    transform: true
  });

  const expected = [
    {userAccountId: 1, firstName: 'Jim', lastName: 'Jenkins'}
  ];

  t.deepEqual(actual, expected);
});

test('update - Case 2', async (t) => {
  const actual = await update({
    pool: t.context.pool,
    table: 'user_account',
    values: {firstName: 'Biff'},
    where: {userAccountId: 1},
    transform: true
  });

  const expected = [
    {userAccountId: 1, firstName: 'Biff', lastName: 'Jenkins'}
  ];

  t.deepEqual(actual, expected);
});

test.after.always('Teardown db', async (t) => {
  await t.context.pool.end();
  await execAsync(`dropdb ${t.context.db}`);
});

